apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rke2-test-deploy
  namespace: argocd
  labels:
      deploy: da-test
spec:
  project: da-test
  source:
    repoURL: 'https://github.com/infn-epics/epik8s-rke2-test.git'
    path: deploy
    targetRevision: main
    helm:
      values: |
          namespace: da-test
          domain: "k8sda.lnf.infn.it"
          ingressClassName: "nginx"
          argocdProject: "da-test"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: da-test
  syncPolicy:
    automated:
      prune: true  # Optional: Automatically remove resources not specified in Helm chart
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
      - Prune=true