apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rke2-test-deploy-deploy
  namespace: argocd
  labels:
      deploy: eli
spec:
  project: default
  source:
    repoURL: 'https://github.com/infn-epics/epik8s-rke2-test.git'
    path: deploy
    targetRevision: main
    helm:
      values: |
          namespace: da-test
          domain: "da"
          ingressClassName: "nginx"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: eli
  syncPolicy:
    automated:
      prune: true  # Optional: Automatically remove resources not specified in Helm chart
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
      - Prune=true